config/routes.rb
Rails.application.routes.draw do

  root "mazes#index"

  resources :mazes, only: [:create, :destroy]

end

app/models/cell.rb
require 'ostruct'

class Cell < ActiveRecord::Base

  OPPOSITES = { north: :south, south: :north, east: :west, west: :east }

  belongs_to :maze

  def remove_wall(direction)
    update_attribute "carved_#{direction}".to_sym, true
  end

  def remove_opposite_wall(direction)
    update_attribute "carved_#{OPPOSITES[direction]}".to_sym, true
  end

  def neighbours
    north_cell = y > 0 ? maze.cell_at(x, y - 1) : nil
    south_cell = y < (maze.height - 1) ? maze.cell_at(x, y + 1) : nil
    east_cell = x < (maze.width - 1) ? maze.cell_at(x + 1, y) : nil
    west_cell = x > 0 ? maze.cell_at(x - 1, y) : nil

    OpenStruct.new(north: north_cell, south: south_cell, east: east_cell, west: west_cell)
  end

end

app/models/maze.rb
class Maze < ActiveRecord::Base

  has_many :cells

  # Create empty grid of cells for future use.
  def generate_base_cells
    width.times do |x|
      height.times do |y|
        cells.build x: x, y: y
      end
    end

    cell_at(0,0).starting_cell = true
    cell_at(width - 1, height - 1).ending_cell = true

    save!
  end

  def columns
    cells.group_by(&:x)
  end

  def rows
    cells.group_by(&:y)
  end

  def cell_at(x, y)
    cells.detect { |c| c.x == x && c.y == y }
  end

  def neighbours(x, y)
    cell_at(x,y).neighbours
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mazes_controller.rb
class MazesController < ApplicationController

  def index
    @mazes = Maze.all.includes(:cells).order(id: :desc)
  end

  def create
    @maze = Maze.create maze_attributes
    @maze.generate_base_cells

    MazeGeneratorService.new(@maze).generate

    flash[:success] = "Maze created!"
    redirect_to root_path
  end

  def destroy
    maze = Maze.find(params[:id])
    maze.destroy

    flash[:success] = "Maze deleted!"
    redirect_to root_path
  end

  private

  def maze_attributes
    params.require(:maze).permit(:width, :height)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mazes_helper.rb
module MazesHelper

  def solve(maze)
    solver = MazeSolverService.new(maze)
    solver.solve
    solver.steps
  end

  def pretty_print_maze(maze)
    output =  "&nbsp;" + "_" * (maze.width * 2 - 1)
    output << "<br>"
    maze.height.times do |y|
      output << "|"
      maze.width.times do |x|
        output << (maze.cell_at(x,y).carved_south? ? "&nbsp;" : "_")
        output << (maze.cell_at(x,y).carved_east? ? "&nbsp;" : "|")
      end

      output << "<br>"
    end

    output
  end

end

app/views/layouts/application.html.haml
!!! 5
%html{ lang: "en" }
  %head
    %meta{ charset: "utf-8" }
    %meta{ http_equiv: "X-UA-Compatible", content: "IE=Edge,chrome=1" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %title= content_for?(:title) ? yield(:title) : "Mazes"
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle{ type: "button",  data: { toggle: "collapse", target: ".navbar-responsive-collapse" } }
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{ href: "#" } Mazes
    .container
      .row
        .col-lg-12
          = yield

app/views/mazes/index.html.haml
.panel.panel-default
  .panel-heading
    %h4 New Maze
  .panel-body
    = form_for :maze, url: mazes_path do |maze_form|
      .form-group
        = maze_form.label :generator
        = maze_form.select :generator, [["Recursive Backtracker","recursive_backtracker"], ["Randomised Kruskals", "randomised_kruskals"], ["Randomised Prims", "randomised_prims"]], {}, class: "form-control"
      .form-group
        = maze_form.label :width
        = maze_form.select :width, (5..20), {}, class: "form-control"
      .form-group
        = maze_form.label :height
        = maze_form.select :height, (5..20), {}, class: "form-control"
      = maze_form.button class: "btn btn-primary" do
        Create Maze

- @mazes.each do |maze|
  .panel.panel-default
    .panel-heading
      .btn-toolbar.pull-right
        .btn-group
          = link_to maze_path(maze), method: :delete, class: "btn btn-danger" do
            Delete Maze
      %h4= maze.generator || "N/A"
    .panel-body
      .row
        .col-xs-4
          %pre
            != pretty_print_maze maze
        .col-xs-8
          %strong Solution
          %br
          - solve(maze).each do |step|
            %span.label.label-success #{step.x},#{step.y}